[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/pascalschaar/"

[[redirects]]
  from = "/github"
  to = "https://github.com/scarlachs"

[[redirects]]
  from = "/photos"
  to = "https://pascal.photos"

[[redirects]]
  from = "/trustpilot"
  to = "https://de.trustpilot.com/review/schaar.dev"